#!/bin/sh

set -e

FROM=$(dirname $0)
TO=quad_mixtape@ssh.nyc1.nearlyfreespeech.net

rsync \
	--archive \
	--partial \
	--progress \
	--delete \
	--delete-excluded \
	--exclude "$(basename $0)" \
	--filter 'dir-merge,e /.rsync-filter' \
	--filter 'protect .well-known/acme-challenge/' \
	$* \
	-- \
	"$FROM" "$TO:"
