#!/bin/sh

set -e

HERE=$(dirname $0)

git ls-files -z $HERE |
rsync \
	--archive \
	--partial \
	--progress \
	--delete \
	--from0 \
	--files-from=- \
	--exclude push \
	--delete-excluded \
	--filter 'protect .well-known/acme-challenge/' \
	-- \
	$HERE quad_mixtape@ssh.nyc1.nearlyfreespeech.net:
